ALTER TABLE public.internal_cron_tokens ENABLE ROW LEVEL SECURITY;
GRANT USAGE ON SCHEMA auth TO sandbox_exec;
GRANT SELECT ON auth.users TO sandbox_exec;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO sandbox_exec;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO sandbox_exec;